### ISSUE TITLE
Junos Ansible Modules moved.

### ISSUE THREAD

**Issue by shermdog** [Juniper/ansible#1]
Hi Everyone,

We have formally submitted our modules for inclusion into Ansible Core.

As part of that process we have consolidated the code and moved it into a fork of the Ansible project.
https://github.com/Juniper/ansible

You can find the code in library/net_infrastructure
https://github.com/Juniper/ansible/tree/juniper-pr/library/net_infrastructure

Official inclusion will be an iterative process, so it may be some time before our pull request is merged.

Thank you everyone for supporting this effort!

**Comment by shermdog** [comment]
@supertylerc
@TerpEE93

**Comment by shermdog** [comment]
This is now wrong.  Per a recent decision by Ansible, our modules will be hosted via Galaxy.

**Comment by RobWC** [comment]
High five!
