### ISSUE TITLE
Getting Error :with newer ansible module ansible-playbook 2.3.2.0

### ISSUE THREAD

**Issue by ashishbhatn** [Juniper/ansible#2]
Getting below error while executing ansible playbook in latest ansible module   2.3.2.0
root@ubuntu:/home/ashish#  ansible-playbook test.yaml   --extra-vars "user=regress passwd=MaRtInI"

PLAY [Gather user information] *****************************************************************************************************************************************

TASK [Gather user information] *****************************************************************************************************************************************
fatal: [10.102.186.24]: FAILED! => {"changed": false, "failed": true, "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell", "rc": 255}
        to retry, use: --limit @/home/ashish/test.retry

PLAY RECAP *************************************************************************************************************************************************************
10.102.186.24              : ok=0    changed=0    unreachable=0    failed=1

ansible playbook : 

---
- name: Gather user information
  hosts: all
  connection: local
  gather_facts: no
  vars:
    credentials:
      username: "{{ user }}"
      password: "{{ passwd }}"
      host: "{{ inventory_hostname }}"
      port: 22
  tasks:
  - name: Gather user information
    junos_command:
      commands:
        - show system users
      provider: "{{ credentials }}"
    register: result
 
  - debug: var=result.stdout

**Comment by dmontagner** [comment]
@ashishbhatn can you please follow the steps highlighted here: [Ansible network troubleshooting](http://docs.ansible.com/ansible/latest/network_debug_troubleshooting.html#unable-to-open-shell) ?

It looks like a credential/authentication issue. You need to follow the procedure above to get to the bottom line of the problem.

Enable the debug logs and then post them here.

./dmontagner

**Comment by ashishbhatn** [comment]
Issue is resolved after implementation of suggestion from Nitin Kumar
https://stackoverflow.com/questions/44562676/ansible-2-3-core-module-junos-config-failed-unable-to-open-shell
